version: '3.1'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql

  myphpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpmyadmin
    ports:
      - "9999:80"
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_ARBITRARY: 1

  backend:
    depends_on:
      - mysqldb
    container_name: backend
    ports:
      - '8040:8040'
    image: nada/backend
    restart: unless-stopped
