version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: ,mounakhattat/5infini-g3-kaddem-4.0
    restart: always
    build: .
    ports:
      - 8066:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3307
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/Kaddem/DevopsProject/db:/var/lib/mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: khaddemApp
      MYSQL_ROOT_PASSWORD: root
