version: '3'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: mysqldb
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - app-network

  backend-container:
    image: nada/imagepost:latest
    #container_name: 83bf6c1359ff
    ports:
      - "8089:8089"

    depends_on:
      - mysqldb
    networks:
      - app-network
  myphpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myphpmyadmin
    ports:
      - "9999:80"
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_ARBITRARY: 1
volumes:
  mysql_data:
  mysql_config:
networks:
  app-network:
    driver: bridge
